version: '3.0'
services:
  kafka:
    build:
      dockerfile: ./kafka/Dockerfile
      args:
        PORT: 29092
    container_name: kafka
    extra_hosts:
      - "broker:0.0.0.0"
    ports:
      - "29092:29092"
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  hbase:
    build:
      dockerfile: ./hbase/Dockerfile
      args:
        MASTER_PORT: 16010
        CLIENT_PORT: 8080
    container_name: hbase
    ports:
      - "16010:16010"
      - "8080:8080"
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
