version: '3.0'
services:
  kafka:
    build:
      dockerfile: ./kafka/Dockerfile
      args:
        PORT: 29092
    extra_hosts:
      - "broker:0.0.0.0"
    ports:
      - "29092:29092"
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  hbase:
    build:
      dockerfile: ./hbase/Dockerfile
      args:
        MASTER_PORT: 16010
        CLIENT_PORT: 8080
    ports:
      - "16010:16010"
      - "8080:8080"
    restart: unless-stopped
