version: '3.0'
services:
  kafka:
    build:
      dockerfile: ./kafka/Dockerfile
      args:
        PORT: 29092
    extra_hosts:
      - "broker:0.0.0.0"
    ports:
      - "29092:29092"
    restart: unless-stopped

